# Site settings
title:       blog.montagmorgen.at
email:       georg.ringer@ggmail.com
author:      Georg Ringer
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://blog.montagmorgen.at"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: georgringer
twitter_username: georg_ringer
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
permalink: /:year/:month/:day/:title.html
